# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-18 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentinfo',
            options={},
        ),
        migrations.AlterModelTable(
            name='customerlinkreord',
            table='department_info',
        ),
    ]
