# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-20 06:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0002_auto_20181218_1554'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='departmentinfo',
            table=None,
        ),
    ]
